//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioMonitor.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardioMonitor.Resources.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные не корректны.
        /// </summary>
        internal static string ArgumentNullExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отказано в доступе к базе данных. Проверьте название базы данных, логин и пароль..
        /// </summary>
        internal static string DataBaseRepository_AccessDeniedException {
            get {
                return ResourceManager.GetString("DataBaseRepository_AccessDeniedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно подключиться к указанному серверу. Проверьте название сервера и порт..
        /// </summary>
        internal static string DataBaseRepository_HostAccessException {
            get {
                return ResourceManager.GetString("DataBaseRepository_HostAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось добавить пациента .
        /// </summary>
        internal static string DataBaseRepository_Patient_AddExcepttion {
            get {
                return ResourceManager.GetString("DataBaseRepository_Patient_AddExcepttion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить пациента.
        /// </summary>
        internal static string DataBaseRepository_Patient_DeleteExcepttion {
            get {
                return ResourceManager.GetString("DataBaseRepository_Patient_DeleteExcepttion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось обновить данные пациента.
        /// </summary>
        internal static string DataBaseRepository_Patient_UpdateExcepttion {
            get {
                return ResourceManager.GetString("DataBaseRepository_Patient_UpdateExcepttion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось получить список пациентов.
        /// </summary>
        internal static string DataBaseRepository_Patients_GetExcepttion {
            get {
                return ResourceManager.GetString("DataBaseRepository_Patients_GetExcepttion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить результаты сеанса.
        /// </summary>
        internal static string DataBaseRepository_Session_AddException {
            get {
                return ResourceManager.GetString("DataBaseRepository_Session_AddException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить сеанс.
        /// </summary>
        internal static string DataBaseRepository_Session_DeleteException {
            get {
                return ResourceManager.GetString("DataBaseRepository_Session_DeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось получить информацию о сеансе.
        /// </summary>
        internal static string DataBaseRepository_Session_GetException {
            get {
                return ResourceManager.GetString("DataBaseRepository_Session_GetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось получить информацию о сеансах.
        /// </summary>
        internal static string DataBaseRepository_SessionInfo_GetException {
            get {
                return ResourceManager.GetString("DataBaseRepository_SessionInfo_GetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалость добавить курс лечения.
        /// </summary>
        internal static string DataBaseRepository_Treatment_AddException {
            get {
                return ResourceManager.GetString("DataBaseRepository_Treatment_AddException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить курс лечения.
        /// </summary>
        internal static string DataBaseRepository_Treatment_DeleteException {
            get {
                return ResourceManager.GetString("DataBaseRepository_Treatment_DeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось получить курсы лечения.
        /// </summary>
        internal static string DataBaseRepository_Treatments_GetException {
            get {
                return ResourceManager.GetString("DataBaseRepository_Treatments_GetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная ошибка при подключении к базе данных.
        /// </summary>
        internal static string DataBaseRepository_UnknownException {
            get {
                return ResourceManager.GetString("DataBaseRepository_UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все несохраненые изменения будут потеряны. Продолжить?.
        /// </summary>
        internal static string LostChangesConfirmation {
            get {
                return ResourceManager.GetString("LostChangesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось получить список.
        /// </summary>
        internal static string MainWindowViewModel_CantLoadList {
            get {
                return ResourceManager.GetString("MainWindowViewModel_CantLoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить пациента?.
        /// </summary>
        internal static string PatientsViewModel_DeletePatientQuestion {
            get {
                return ResourceManager.GetString("PatientsViewModel_DeletePatientQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пациент добавлен!.
        /// </summary>
        internal static string PatientViewModel_Patient_Added {
            get {
                return ResourceManager.GetString("PatientViewModel_Patient_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменения сохранены!.
        /// </summary>
        internal static string PatientViewModel_Patient_Updated {
            get {
                return ResourceManager.GetString("PatientViewModel_Patient_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление пациента.
        /// </summary>
        internal static string PatientViewModel_Title_Add {
            get {
                return ResourceManager.GetString("PatientViewModel_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование данных пациента.
        /// </summary>
        internal static string PatientViewModel_Title_Edit {
            get {
                return ResourceManager.GetString("PatientViewModel_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить сессию?.
        /// </summary>
        internal static string SessionsViewModel_DeleteSessionQuestion {
            get {
                return ResourceManager.GetString("SessionsViewModel_DeleteSessionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пауза.
        /// </summary>
        internal static string SessionViewModel_PauseButton_Text {
            get {
                return ResourceManager.GetString("SessionViewModel_PauseButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные не корректны.
        /// </summary>
        internal static string SessionViewModel_SaveSession_ArgumentNullException {
            get {
                return ResourceManager.GetString("SessionViewModel_SaveSession_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сеанс завершен.
        /// </summary>
        internal static string SessionViewModel_SessionCompeted {
            get {
                return ResourceManager.GetString("SessionViewModel_SessionCompeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старт.
        /// </summary>
        internal static string SessionViewModel_StartButton_Text {
            get {
                return ResourceManager.GetString("SessionViewModel_StartButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите каталог для хранения результатов сеансов.
        /// </summary>
        internal static string SettingsViewModel_ChooseFolder {
            get {
                return ResourceManager.GetString("SettingsViewModel_ChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указанной директории не существует..
        /// </summary>
        internal static string SettingsViewModel_DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("SettingsViewModel_DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки сохранены.
        /// </summary>
        internal static string SettingsViewModel_Saved {
            get {
                return ResourceManager.GetString("SettingsViewModel_Saved", resourceCulture);
            }
        }
    }
}
