//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioMonitor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardioMonitor.Resources.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные не корректны.
        /// </summary>
        internal static string ArgumentNullExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказано в доступе к базе данных. Проверьте название базы данных, логин и пароль..
        /// </summary>
        internal static string DataBaseRepository_AccessDeniedException {
            get {
                return ResourceManager.GetString("DataBaseRepository_AccessDeniedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно подключиться к указанному серверу. Проверьте название сервера и порт..
        /// </summary>
        internal static string DataBaseRepository_HostAccessException {
            get {
                return ResourceManager.GetString("DataBaseRepository_HostAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить пациента .
        /// </summary>
        internal static string DataBaseRepository_Patient_AddExcepttion {
            get {
                return ResourceManager.GetString("DataBaseRepository_Patient_AddExcepttion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить пациента.
        /// </summary>
        internal static string DataBaseRepository_Patient_DeleteExcepttion {
            get {
                return ResourceManager.GetString("DataBaseRepository_Patient_DeleteExcepttion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить данные пациента.
        /// </summary>
        internal static string DataBaseRepository_Patient_UpdateExcepttion {
            get {
                return ResourceManager.GetString("DataBaseRepository_Patient_UpdateExcepttion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить список пациентов.
        /// </summary>
        internal static string DataBaseRepository_Patients_GetExcepttion {
            get {
                return ResourceManager.GetString("DataBaseRepository_Patients_GetExcepttion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сохранить результаты сеанса.
        /// </summary>
        internal static string DataBaseRepository_Session_AddException {
            get {
                return ResourceManager.GetString("DataBaseRepository_Session_AddException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить сеанс.
        /// </summary>
        internal static string DataBaseRepository_Session_DeleteException {
            get {
                return ResourceManager.GetString("DataBaseRepository_Session_DeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить информацию о сеансе.
        /// </summary>
        internal static string DataBaseRepository_Session_GetException {
            get {
                return ResourceManager.GetString("DataBaseRepository_Session_GetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить информацию о сеансах.
        /// </summary>
        internal static string DataBaseRepository_SessionInfo_GetException {
            get {
                return ResourceManager.GetString("DataBaseRepository_SessionInfo_GetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалость добавить курс лечения.
        /// </summary>
        internal static string DataBaseRepository_Treatment_AddException {
            get {
                return ResourceManager.GetString("DataBaseRepository_Treatment_AddException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить курс лечения.
        /// </summary>
        internal static string DataBaseRepository_Treatment_DeleteException {
            get {
                return ResourceManager.GetString("DataBaseRepository_Treatment_DeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить курсы лечения.
        /// </summary>
        internal static string DataBaseRepository_Treatments_GetException {
            get {
                return ResourceManager.GetString("DataBaseRepository_Treatments_GetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка при подключении к базе данных.
        /// </summary>
        internal static string DataBaseRepository_UnknownException {
            get {
                return ResourceManager.GetString("DataBaseRepository_UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалость загрузить информация о сеансе из файла.
        /// </summary>
        internal static string FileRepository_LoadPatientException {
            get {
                return ResourceManager.GetString("FileRepository_LoadPatientException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалость сохранить информация о сеансе в файл.
        /// </summary>
        internal static string FileRepository_SavePatientException {
            get {
                return ResourceManager.GetString("FileRepository_SavePatientException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сеанс|*.cmsf.
        /// </summary>
        internal static string FileRepository_SeansFileFilter {
            get {
                return ResourceManager.GetString("FileRepository_SeansFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все несохраненые изменения будут потеряны. Продолжить?.
        /// </summary>
        internal static string LostChangesConfirmation {
            get {
                return ResourceManager.GetString("LostChangesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить список.
        /// </summary>
        internal static string MainWindowViewModel_CantLoadList {
            get {
                return ResourceManager.GetString("MainWindowViewModel_CantLoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить пациента?.
        /// </summary>
        internal static string PatientsViewModel_DeletePatientQuestion {
            get {
                return ResourceManager.GetString("PatientsViewModel_DeletePatientQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пациент добавлен!.
        /// </summary>
        internal static string PatientViewModel_Patient_Added {
            get {
                return ResourceManager.GetString("PatientViewModel_Patient_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменения сохранены!.
        /// </summary>
        internal static string PatientViewModel_Patient_Updated {
            get {
                return ResourceManager.GetString("PatientViewModel_Patient_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление пациента.
        /// </summary>
        internal static string PatientViewModel_Title_Add {
            get {
                return ResourceManager.GetString("PatientViewModel_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование данных пациента.
        /// </summary>
        internal static string PatientViewModel_Title_Edit {
            get {
                return ResourceManager.GetString("PatientViewModel_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл сохранен.
        /// </summary>
        internal static string SessionDataViewModel_FileSaved {
            get {
                return ResourceManager.GetString("SessionDataViewModel_FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить сессию?.
        /// </summary>
        internal static string SessionsViewModel_DeleteSessionQuestion {
            get {
                return ResourceManager.GetString("SessionsViewModel_DeleteSessionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пауза.
        /// </summary>
        internal static string SessionViewModel_PauseButton_Text {
            get {
                return ResourceManager.GetString("SessionViewModel_PauseButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные не корректны.
        /// </summary>
        internal static string SessionViewModel_SaveSession_ArgumentNullException {
            get {
                return ResourceManager.GetString("SessionViewModel_SaveSession_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сеанс завершен.
        /// </summary>
        internal static string SessionViewModel_SessionCompeted {
            get {
                return ResourceManager.GetString("SessionViewModel_SessionCompeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт.
        /// </summary>
        internal static string SessionViewModel_StartButton_Text {
            get {
                return ResourceManager.GetString("SessionViewModel_StartButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите каталог для хранения результатов сеансов.
        /// </summary>
        internal static string SettingsViewModel_ChooseFolder {
            get {
                return ResourceManager.GetString("SettingsViewModel_ChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанной директории не существует..
        /// </summary>
        internal static string SettingsViewModel_DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("SettingsViewModel_DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки сохранены.
        /// </summary>
        internal static string SettingsViewModel_Saved {
            get {
                return ResourceManager.GetString("SettingsViewModel_Saved", resourceCulture);
            }
        }
    }
}
